<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
Dataset <- 
  read.table("C:/Users/pc 1/Desktop/PAQUETE R/PRACTICAS-_1/datos01.dat", 
  header=TRUE, stringsAsFactors=TRUE, sep="", na.strings="NA", dec=".", 
  strip.white=TRUE)
```

```{r}
Datos <- 
  readXL("C:/Users/pc 1/Desktop/PAQUETE R/PRACTICAS-_1/contaminacion_mexico.xls",
   rownames=FALSE, header=TRUE, na="", sheet="contaminacion_mexico", 
  stringsAsFactors=TRUE)
```

```{r}
Data <- readSPSS("C:/Users/pc 1/Desktop/PAQUETE R/PRACTICAS-_1/demo.sav", 
  rownames=FALSE, stringsAsFactors=TRUE, tolower=FALSE)
```

